# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'win10_notepad_L4.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QFrame, QLayout,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QSizePolicy, QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(862, 561)
        self.action_N = QAction(MainWindow)
        self.action_N.setObjectName(u"action_N")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_O = QAction(MainWindow)
        self.action_O.setObjectName(u"action_O")
        self.action_S = QAction(MainWindow)
        self.action_S.setObjectName(u"action_S")
        self.action_A = QAction(MainWindow)
        self.action_A.setObjectName(u"action_A")
        self.action_U = QAction(MainWindow)
        self.action_U.setObjectName(u"action_U")
        self.action_P = QAction(MainWindow)
        self.action_P.setObjectName(u"action_P")
        self.action_X = QAction(MainWindow)
        self.action_X.setObjectName(u"action_X")
        self.action_U_2 = QAction(MainWindow)
        self.action_U_2.setObjectName(u"action_U_2")
        self.action_U_2.setEnabled(False)
        self.action_T = QAction(MainWindow)
        self.action_T.setObjectName(u"action_T")
        self.action_T.setEnabled(False)
        self.action_C = QAction(MainWindow)
        self.action_C.setObjectName(u"action_C")
        self.action_C.setEnabled(False)
        self.action_P_2 = QAction(MainWindow)
        self.action_P_2.setObjectName(u"action_P_2")
        self.action_P_2.setEnabled(False)
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.action_5.setEnabled(False)
        self.action_Bing = QAction(MainWindow)
        self.action_Bing.setObjectName(u"action_Bing")
        self.action_Bing.setEnabled(False)
        self.action_F = QAction(MainWindow)
        self.action_F.setObjectName(u"action_F")
        self.action_F.setEnabled(False)
        self.action_N_2 = QAction(MainWindow)
        self.action_N_2.setObjectName(u"action_N_2")
        self.action_N_2.setEnabled(False)
        self.action_V = QAction(MainWindow)
        self.action_V.setObjectName(u"action_V")
        self.action_V.setEnabled(False)
        self.action_R = QAction(MainWindow)
        self.action_R.setObjectName(u"action_R")
        self.action_G = QAction(MainWindow)
        self.action_G.setObjectName(u"action_G")
        self.action_G.setCheckable(False)
        self.action_G.setEnabled(False)
        self.action_A_2 = QAction(MainWindow)
        self.action_A_2.setObjectName(u"action_A_2")
        self.action_D = QAction(MainWindow)
        self.action_D.setObjectName(u"action_D")
        self.action_W = QAction(MainWindow)
        self.action_W.setObjectName(u"action_W")
        self.action_W.setCheckable(True)
        self.action_W.setChecked(True)
        self.action_F_2 = QAction(MainWindow)
        self.action_F_2.setObjectName(u"action_F_2")
        self.action_S_2 = QAction(MainWindow)
        self.action_S_2.setObjectName(u"action_S_2")
        self.action_S_2.setCheckable(True)
        self.action_S_2.setChecked(True)
        self.action_S_2.setEnabled(True)
        self.action_I = QAction(MainWindow)
        self.action_I.setObjectName(u"action_I")
        self.action_O_2 = QAction(MainWindow)
        self.action_O_2.setObjectName(u"action_O_2")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.action_H = QAction(MainWindow)
        self.action_H.setObjectName(u"action_H")
        self.action_F_3 = QAction(MainWindow)
        self.action_F_3.setObjectName(u"action_F_3")
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setFrameShape(QFrame.Shape.Panel)
        self.plainTextEdit.setFrameShadow(QFrame.Shadow.Raised)
        self.plainTextEdit.setLineWidth(0)
        self.plainTextEdit.setMidLineWidth(1)
        self.plainTextEdit.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.plainTextEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.plainTextEdit.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)

        self.verticalLayout.addWidget(self.plainTextEdit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 862, 27))
        self.menu_F = QMenu(self.menubar)
        self.menu_F.setObjectName(u"menu_F")
        self.menu_E = QMenu(self.menubar)
        self.menu_E.setObjectName(u"menu_E")
        self.menu_O = QMenu(self.menubar)
        self.menu_O.setObjectName(u"menu_O")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_Z = QMenu(self.menu)
        self.menu_Z.setObjectName(u"menu_Z")
        self.menu_H = QMenu(self.menubar)
        self.menu_H.setObjectName(u"menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setAutoFillBackground(False)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_E.menuAction())
        self.menubar.addAction(self.menu_O.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menu_F.addAction(self.action_N)
        self.menu_F.addAction(self.action)
        self.menu_F.addAction(self.action_O)
        self.menu_F.addAction(self.action_S)
        self.menu_F.addAction(self.action_A)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_U)
        self.menu_F.addAction(self.action_P)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.action_X)
        self.menu_E.addAction(self.action_U_2)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.action_T)
        self.menu_E.addAction(self.action_C)
        self.menu_E.addAction(self.action_P_2)
        self.menu_E.addAction(self.action_5)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.action_Bing)
        self.menu_E.addAction(self.action_F)
        self.menu_E.addAction(self.action_N_2)
        self.menu_E.addAction(self.action_V)
        self.menu_E.addAction(self.action_R)
        self.menu_E.addAction(self.action_G)
        self.menu_E.addSeparator()
        self.menu_E.addAction(self.action_A_2)
        self.menu_E.addAction(self.action_D)
        self.menu_O.addAction(self.action_W)
        self.menu_O.addAction(self.action_F_2)
        self.menu.addAction(self.menu_Z.menuAction())
        self.menu.addAction(self.action_S_2)
        self.menu_Z.addAction(self.action_I)
        self.menu_Z.addAction(self.action_O_2)
        self.menu_Z.addAction(self.action_2)
        self.menu_H.addAction(self.action_H)
        self.menu_H.addAction(self.action_F_3)
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.action_4)

        self.retranslateUi(MainWindow)
        self.action_S_2.toggled.connect(self.statusbar.setHidden)
        self.action_S_2.toggled.connect(self.statusbar.setVisible)
        self.action_X.triggered.connect(MainWindow.close)
        self.action_A_2.triggered.connect(self.plainTextEdit.selectAll)
        self.action_I.triggered.connect(self.plainTextEdit.zoomIn)
        self.action_O_2.triggered.connect(self.plainTextEdit.zoomOut)
        self.action_U_2.triggered.connect(self.plainTextEdit.undo)
        self.action_T.triggered.connect(self.plainTextEdit.cut)
        self.action_P_2.triggered.connect(self.plainTextEdit.paste)
        self.action_5.triggered.connect(self.plainTextEdit.clear)
        self.plainTextEdit.copyAvailable.connect(self.action_U_2.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_P_2.resetEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_T.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_5.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_F.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_V.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_N_2.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_Bing.setEnabled)
        self.plainTextEdit.copyAvailable.connect(self.action_C.setEnabled)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u65e0\u6807\u9898-\u8bb0\u4e8b\u672c", None))
        self.action_N.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa(&N)", None))
#if QT_CONFIG(shortcut)
        self.action_N.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u7a97\u53e3(&W)", None))
#if QT_CONFIG(shortcut)
        self.action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_O.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00(&O)", None))
#if QT_CONFIG(shortcut)
        self.action_O.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_S.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58(&S)", None))
#if QT_CONFIG(shortcut)
        self.action_S.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_A.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a(A)", None))
#if QT_CONFIG(shortcut)
        self.action_A.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_U.setText(QCoreApplication.translate("MainWindow", u"\u9875\u9762\u8bbe\u7f6e(&U)", None))
        self.action_P.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5370(&P)", None))
#if QT_CONFIG(shortcut)
        self.action_P.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.action_X.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa(&X)", None))
        self.action_U_2.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500(&U)", None))
#if QT_CONFIG(shortcut)
        self.action_U_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_T.setText(QCoreApplication.translate("MainWindow", u"\u526a\u5207(&T)", None))
#if QT_CONFIG(shortcut)
        self.action_T.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_C.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236(C)", None))
#if QT_CONFIG(shortcut)
        self.action_C.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.action_P_2.setText(QCoreApplication.translate("MainWindow", u"\u7c98\u8d34(P)", None))
#if QT_CONFIG(shortcut)
        self.action_P_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664(L)", None))
#if QT_CONFIG(shortcut)
        self.action_5.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.action_Bing.setText(QCoreApplication.translate("MainWindow", u"\u4f7f\u7528Bing\u641c\u7d22", None))
#if QT_CONFIG(shortcut)
        self.action_Bing.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.action_F.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e(&F)", None))
#if QT_CONFIG(shortcut)
        self.action_F.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_N_2.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u4e0b\u4e00\u4e2a(&N)", None))
#if QT_CONFIG(shortcut)
        self.action_N_2.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.action_V.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u4e0a\u4e00\u4e2a(&V)", None))
#if QT_CONFIG(shortcut)
        self.action_V.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+F3", None))
#endif // QT_CONFIG(shortcut)
        self.action_R.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362(&R)", None))
#if QT_CONFIG(shortcut)
        self.action_R.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.action_G.setText(QCoreApplication.translate("MainWindow", u" \u8f6c\u5230(&G)", None))
#if QT_CONFIG(shortcut)
        self.action_G.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.action_A_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u9009(&A)", None))
#if QT_CONFIG(shortcut)
        self.action_A_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_D.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u95f4/\u65e5\u671f(&D)", None))
#if QT_CONFIG(shortcut)
        self.action_D.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.action_W.setText(QCoreApplication.translate("MainWindow", u"\u81ea\u52a8\u6362\u884c(&W)", None))
        self.action_F_2.setText(QCoreApplication.translate("MainWindow", u"\u5b57\u4f53(&F)", None))
        self.action_S_2.setText(QCoreApplication.translate("MainWindow", u"\u72b6\u6001\u680f(&S)", None))
        self.action_I.setText(QCoreApplication.translate("MainWindow", u"\u653e\u5927(&I)", None))
#if QT_CONFIG(shortcut)
        self.action_I.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+=", None))
#endif // QT_CONFIG(shortcut)
        self.action_O_2.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u5c0f(&O)", None))
#if QT_CONFIG(shortcut)
        self.action_O_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u9ed8\u8ba4\u7f29\u653e", None))
#if QT_CONFIG(shortcut)
        self.action_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+0", None))
#endif // QT_CONFIG(shortcut)
        self.action_H.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u5e2e\u52a9(&H)", None))
        self.action_F_3.setText(QCoreApplication.translate("MainWindow", u"\u53d1\u9001\u53cd\u9988(&F)", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e\u8bb0\u4e8b\u672c(&A)", None))
        self.menu_F.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6(&F)", None))
        self.menu_E.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91(&E)", None))
        self.menu_O.setTitle(QCoreApplication.translate("MainWindow", u"\u683c\u5f0f(&O)", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u67e5\u770b(&V)", None))
        self.menu_Z.setTitle(QCoreApplication.translate("MainWindow", u"\u7f29\u653e(&Z)", None))
        self.menu_H.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9(&H)", None))
    # retranslateUi

